import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery, gql } from "@apollo/client"
import { useEffect, useState } from 'react'

const GET_IMAGE = gql`
{
  getImage {
    url
    title
    explanation
  }
}`

export default function Home() {
  const { loading, error, data } = useQuery(GET_IMAGE)
  const [url, setURL] = useState('')
  const [title, setTitle] = useState('')
  const [explanation, setExplanation] = useState('')


  useEffect(() => {
    console.log(data?.getImage)
    setURL(data?.getImage.url)
    setTitle(data?.getImage.title)
    setExplanation(data?.getImage.explanation)

  }, [data])

  if (error)
    console.log(error)
  return (
    <div className={styles.container}>
      <Head>
        <title>Next and Graphql App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        data &&
        <>
          <h1>{title}</h1>
          <div style={{
            width: '30rem'
          }}>
            <Image src={url} alt="Image" width={1} height={1} layout="responsive" />
          </div>
          <p>
            {
              explanation
            }
          </p>
        </>
      }
    </div>
  )
}
